services:
  nginx:
    build:
        context: .
        dockerfile: docker/nginx/Dockerfile
    image: ghcr.io/luka-lta/linkifyr/api-nginx:dev
    container_name: 'nginx-linkifyr'
    ports:
      - '80:80'
    volumes:
      - ./public:/app/public:rw
      - ./docker/nginx/nginx-development.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm-api
    networks:
      - linkifyr-shared

  php-fpm-api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: development
    image: ghcr.io/luka-lta/linkifyr/api-php-fpm:dev
    container_name: 'php-fpm-linkifyr'
    working_dir: /app
    environment:
      APP_ENV: 'development'
      MYSQL_DATABASE: 'linkifyr'
      MYSQL_HOST: 'mysql-linkifyr'
      MYSQL_USER: 'testing'
      MYSQL_PASSWORD: '1234'
      REDIS_HOST: 'redis-linkifyr'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: '1234'
      JWT_SECRET: 'D17c14F3ff!470cEbe5f85df1efc966b0Fcdc@2096'
      JWT_NORMAL_EXPIRATION_TIME: 86400
      JWT_EXTENDED_EXPIRATION_TIME: 604800
      LOG_LEVEL: 'debug'
      LOG_FILE_PATH: '/app/logs'
    volumes:
      - ./:/app:rw
    networks:
      - linkifyr-shared

  mysql:
    image: mysql
    container_name: 'mysql-linkifyr'
    hostname: mysql-linkifyr
    environment:
      MYSQL_DATABASE: 'linkifyr'
      MYSQL_USER: 'testing'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql:rw
      - ./data/mysql:/docker-entrypoint-initdb.d/:ro
    networks:
      - linkifyr-shared

  phpmyadmin:
    image: phpmyadmin
    container_name: 'pma-linkifyr'
    links:
      - mysql
    environment:
      PMA_HOST: mysql-linkifyr
      PMA_PORT: 3306
      PMA_ARBITRAY: 1
    ports:
      - '8081:80'
    networks:
      - linkifyr-shared

  redis:
    image: redis:7.4.1
    container_name: 'redis-linkifyr'
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 1234
    command: [ "redis-server", "--requirepass", "$$REDIS_PASSWORD" ]
    networks:
      - linkifyr-shared
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:

networks:
  linkifyr-shared:
    driver: bridge